"""Git service interactions."""

import subprocess
from pathlib import Path

from rich.console import Console

from infractl.config import ClusterConfig

console = Console()


class GitService:
    """Service for Git operations."""

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = repo_root

    def add(self, path: Path | str) -> None:
        """Stage a file or directory."""
        subprocess.run(
            ["git", "add", str(path)],
            cwd=self.repo_root,
            check=True,
        )

    def has_staged_changes(self) -> bool:
        """Check if there are staged changes."""
        result = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=self.repo_root,
        )
        return result.returncode != 0

    def commit(self, message: str) -> None:
        """Create a commit with the staged changes."""
        subprocess.run(
            ["git", "commit", "-m", message],
            cwd=self.repo_root,
            check=True,
        )

    def push(self) -> None:
        """Push changes to remote."""
        subprocess.run(
            ["git", "push"],
            cwd=self.repo_root,
            check=True,
        )

    def commit_and_push(self, config: ClusterConfig, files: list[Path]) -> None:
        """Stage, commit, and push infrastructure changes."""
        for f in files:
            self.add(f)

        if not self.has_staged_changes():
            console.print("[yellow]No changes to commit[/yellow]")
            return

        message = f"""feat({config.environment.value}): import existing infrastructure for {config.cluster_name}

Auto-generated by infractl bootstrap:
- VPC: {config.vpc_id}
- Region: {config.region}
- Account: {config.account_id}
- OIDC: {config.oidc_id}
"""

        self.commit(message)
        self.push()
        console.print("[green]Changes committed and pushed to git[/green]")
